apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../default

# Configuración de desarrollo
replicas:
  - name: chaos-operator
    count: 1

# Patches para desarrollo
patches:
  - target:
      kind: Deployment
      name: chaos-operator
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: "IfNotPresent"
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: LOG_LEVEL
          value: "debug"

# Imagen local
images:
  - name: goland-operator
    newName: goland-operator
    newTag: latest
