apiVersion: chaos.engineering.io/v1alpha1
kind: StressChaos
metadata:
  name: cpu-stress
  namespace: chaos-demo
spec:
  # 1 pod seleccionado aleatoriamente con 4 workers yes (saturación total de CPU)
  mode: one
  selector:
    namespaces:
      - chaos-demo
    labelSelectors:
      app: nginx
  stressors:
    cpu:
      workers: 4
      load: 100
  duration: "15m"
