apiVersion: chaos.engineering.io/v1alpha1
kind: NetworkChaos
metadata:
  name: network-partition
  namespace: chaos-demo
spec:
  mode: fixed-percent
  value: "50"
  selector:
    namespaces:
      - chaos-demo
    labelSelectors:
      app: apache-target
  action: partition
  direction: both
  target:
    selector:
      namespaces:
        - chaos-demo
      labelSelectors:
        app: nginx
    mode: fixed-percent
    value: "50"
  duration: "2m"
